### ISSUE TITLE
There are no contents here.

### ISSUE THREAD

**Issue by varvir** [MicrosoftDocs/cpp-docs.ko-kr#1005]
Just same as the title, there are no contents here. 
What's wrong? I want to get some information about llvm/clang in Visual Studio.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 47cabdd4-5ef1-1c19-4a82-5448a5901e8a
* Version Independent ID: 56fd7d96-62ec-07df-40df-aaf155d504d3
* Content: [Visual Studio 프로젝트의 Clang/LLVM 지원](https://docs.microsoft.com/ko-kr/cpp/build/clang-support-msbuild?view=msvc-160)
* Content Source: [docs/build/clang-support-msbuild.md](https://github.com/MicrosoftDocs/cpp-docs.ko-kr/blob/live/docs/build/clang-support-msbuild.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@JasonCard FYI

**Comment by JasonCard** [comment]
Hi @varvir 
It looks like the [Korean content](https://docs.microsoft.com/ko-kr/cpp/build/clang-support-msbuild?view=msvc-160) is displayed correctly now. Please let me know if you're still not able to see the content.
cc @corob-msft
