### ISSUE TITLE
CTabCtrl 클래스 설명서 수정 요청

### ISSUE THREAD

**Issue by leejiwon8433** [MicrosoftDocs/cpp-docs.ko-kr#1006]
[여기에 피드백 입력]
CTabCtrl 클래스에 대한 설명에서 수정이 필요합니다!
CTabCtrl::D~에 있는 모든 항목이 띄어 쓰기가 잘못 돼있습니다.
ex) CTabCtrl::D eleteAllItems -> CTabCtrl:: DeleteAllItems
![image](https://user-images.githubusercontent.com/54174576/105931787-2e66a200-608f-11eb-87a0-7d235ff50a31.png)

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 08fb396a-10e2-a8cb-f55e-64d8cc5136c2
* Version Independent ID: 02013ef1-070e-daef-c89b-32d1aeb3406a
* Content: [CTabCtrl 클래스](https://docs.microsoft.com/ko-kr/cpp/mfc/reference/ctabctrl-class?view=msvc-160)
* Content Source: [docs/mfc/reference/ctabctrl-class.md](https://github.com/MicrosoftDocs/cpp-docs.ko-kr/blob/live/docs/mfc/reference/ctabctrl-class.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Hello, the translation tool doesn't do a good job on your comments here, but I think I know what's wrong.
I have code escaped hundreds of places that should not be machine translated. This fix will be live hopefully by end of day Monday (2/1/2021)
Thank you for pointing this out so we could fix it.
