### ISSUE TITLE
CONTRIBUTING.md is missing

### ISSUE THREAD

**Issue by sftblw** [MicrosoftDocs/cpp-docs.ko-kr#2]
I'd like to edit some parts which are look a bit strange, but `CONTRIBUTING.md` the contribution guide looks missing.

**Comment by CeciAc** [comment]
Thanks for your comment, @sftblw 
We are investigating this issue

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Assigned to owner to check this issue
@nokura

**Comment by nokura** [comment]
Hello @sftblw 
Thank you for your feedback. We have unified contribution guide for docs.microsoft.com. Will you refer to this page? https://docs.microsoft.com/contribute/ 
Kind regards,
Microsoft DOCS International Team
