### ISSUE TITLE
long long 범위 검색 오류

### ISSUE THREAD

**Issue by shininghyunho** [MicrosoftDocs/cpp-docs.ko-kr#599]
구글에 'long long 범위'라고 검색하면 현재 페이지와 다른 검색 결과가 나옵니다.  수정 바랍니다.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 2a3252f3-2390-77d1-75ee-00ff08584173
* Version Independent ID: 53786641-f25d-638f-18d5-8c7e19712776
* Content: [데이터 형식 범위](https://docs.microsoft.com/ko-kr/cpp/cpp/data-type-ranges?view=vs-2017#feedback)
* Content Source: [docs/cpp/data-type-ranges.md](https://github.com/MicrosoftDocs/cpp-docs.ko-kr/blob/live/docs/cpp/data-type-ranges.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by CeciAc** [comment]
안녕하세요. , @shininghyunho 
피드백을 주셔서 감사합니다. 
사용자의 의견을 적극적으로 검토하고 있으며 곧 답변을 드리겠습니다. 
감사합니다. 
Microsoft DOCS 국제 팀

**Comment by CeciAc** [comment]
안녕하세요. , @shininghyunho
피드백을 주셔서 감사합니다. 
 당사의 엔지니어링 팀이 귀하의 제안 사항을 검토하고 수락했습니다. 귀하의 피드백을 반영하여 Docs 사이트의 업데이트된 문서의 다음 페이지 https://docs.microsoft.com/ko-kr/cpp/cpp/data-type-ranges?view=vs-2017#feedback 에 게시했습니다.  
 당사의 문서에 대한 귀하의 기여에 진심으로 감사 드리며 소중한 피드백을 계속 주시기 바랍니다. 
 감사합니다.
Microsoft DOCS 국제 팀
