### ISSUE TITLE
더 나은 파라미터 해석 more better parameter description translate

### ISSUE THREAD

**Issue by PangPangs** [MicrosoftDocs/cpp-docs.ko-kr#639]
number
Array size in elements.
&gt;&gt; 이 부분은
number
대상 배열의 길이입니다.

가 좀더 나은 표현같습니다.
---
number
Array size in elements.
&gt;&gt; translate
number
대상 배열의 길이입니다.

is more better translating, I think

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 135f5795-2d27-fded-f416-2f5723b85b14
* Version Independent ID: 245a2a7a-b1b4-dcc3-9581-9d6101ed0292
* Content: [qsort](https://docs.microsoft.com/ko-kr/cpp/c-runtime-library/reference/qsort?view=vs-2019#feedback)
* Content Source: [docs/c-runtime-library/reference/qsort.md](https://github.com/MicrosoftDocs/cpp-docs.ko-kr/blob/live/docs/c-runtime-library/reference/qsort.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by CeciAc** [comment]
Hello, @PangPangs
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
안녕하세요. @PangPangs  님,
댓글을 남겨 주셔서 감사드리며 Microsoft는 docs.microsoft.com의 환경을 개선하기 위해 노력하고 있습니다. 그러나 귀하의 의견을 처리하기 위해서는 추가 정보가 필요합니다. 자세한 정보를 제공하고 댓글에 대해 명확하게 설명해 주실 수 있으신지요?
감사합니다.
Microsoft DOCS International 팀

**Comment by PangPangs** [comment]
한국어에서 크기와 길이는 의미적으로 차이가 있습니다. 영어에서는 크기와 길이를 혼용하는지는 모르겠습니다만, 한국의 초보 개발자를 위해 의미적으로 더 명확하다고 느껴 교정을 요청드렸습니다.

**Comment by CeciAc** [comment]
안녕하세요. @PangPangs 님,
피드백을 주셔서 감사합니다. 
사용자의 의견을 적극적으로 검토하고 있으며 곧 답변을 드리겠습니다. 
감사합니다. 
Microsoft DOCS 국제 팀

**Comment by CeciAc** [comment]
안녕하세요, @PangPangs  님.  
 피드백을 주셔서 감사합니다. 
 당사의 언어 팀이 귀하의 언어 제안을 검토하고 수용했습니다. 귀하의 피드백을 반영하여 Docs 사이트의 업데이트된 문서의 다음 페이지 https://docs.microsoft.com/ko-kr/cpp/c-runtime-library/reference/qsort?view=vs-2019#feedback 에 게시했습니다.  
 당사의 문서에 대한 귀하의 기여에 진심으로 감사 드리며 소중한 피드백을 계속 주시기 바랍니다. 
 감사합니다. 
Microsoft DOCS 국제 팀
