### ISSUE TITLE
젠투제품에는 연결되지않습니다.

### ISSUE THREAD

**Issue by babeltwr** [MicrosoftDocs/cpp-docs.ko-kr#705]
여러 OS 를 설정해서 사용중인데 연결되지 않는 서버들이 있습니다.
putty 로는 연결되는데 위의 항목으로는 연결되지 않습니다.
원인을 알수있도록 좀더 상세한 접속에러에대한 정보를 표시해주시면 감사하겠습니다.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 77337ba5-50f6-b474-89db-dd51bd8b560d
* Version Independent ID: cdc28c8a-a50e-f6d6-bf25-f5d80b056a5a
* Content: [Visual Studio에서 원격 Linux 컴퓨터에 연결](https://docs.microsoft.com/ko-kr/cpp/linux/connect-to-your-remote-linux-computer?view=vs-2019#feedback)
* Content Source: [docs/linux/connect-to-your-remote-linux-computer.md](https://github.com/MicrosoftDocs/cpp-docs.ko-kr/blob/live/docs/linux/connect-to-your-remote-linux-computer.md)
* Product: **visual-cpp**
* Technology: **cpp-linux**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by CeciAc** [comment]
안녕하세요, @babeltwr 님. 
 귀하의 기여에 매우 감사 드립니다. 당사의 팀만이 설명서와 관련된 피드백에 응답할 수 있습니다. 
 DOCS 페이지 하단에 있는 "제품 피드백 제공" 버튼을 사용하여 귀하의 제품 피드백을 기록해주세요. 
 설명서와 관련된 피드백이 있는 경우 이 채널을 통해 자유롭게 기록해주세요. 
 당사 문서에 대한 귀하의 기여에 진심으로 감사 드립니다.  
 감사합니다.
Microsoft DOCS 국제 팀
