### ISSUE TITLE
자동 번역해서 보여주는 건가요?

### ISSUE THREAD

**Issue by 2kindsofcs** [MicrosoftDocs/cpp-docs.ko-kr#745]
굉장히 어색한 문장들이 보이는데, 사람이 번역한 게 아니라 번역기 돌린 텍스트를 그대로 보여주는 건가요?

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 9d8f4cb9-2629-1ea5-86b1-f74df9c5e86b
* Version Independent ID: f320eb63-0320-769e-498c-b4dc008ce1ce
* Content: [네임스페이스 (C++)](https://docs.microsoft.com/ko-kr/cpp/cpp/namespaces-cpp?view=vs-2019#feedback)
* Content Source: [docs/cpp/namespaces-cpp.md](https://github.com/MicrosoftDocs/cpp-docs.ko-kr/blob/live/docs/cpp/namespaces-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by CeciAc** [comment]
안녕하세요. , @2kindsofcs 
피드백을 주셔서 감사합니다. 
사용자의 의견을 적극적으로 검토하고 있으며 곧 답변을 드리겠습니다. 
감사합니다. 
Microsoft DOCS 국제 팀

**Comment by CeciAc** [comment]
안녕하세요. , @2kindsofcs
피드백을 주셔서 감사합니다. 문제의 페이지가 기계 번역되어 항상 완벽하게 이해할 수 있는 것은 아닙니다. 최근에 오른쪽에 "영어로 읽기" 옵션이 추가되어 언어 설정을 변경하지 않고도 영어 버전으로 전환할 수 있습니다. 
감사합니다.
Microsoft DOCS 국제 팀
