### ISSUE TITLE
문법 교정

### ISSUE THREAD

**Issue by stargt** [MicrosoftDocs/cpp-docs.ko-kr#852]
유니버설 Windows 플랫폼(UWP) 비교하여 -&gt; 유니버설 Windows 플랫폼(UWP)과 비교하여

로 변경되어야 자연스러운 것 같음

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 8c828ff7-367e-cdb9-7573-69e3f87f27a2
* Version Independent ID: 39f4562b-606c-4a6a-150a-eade928a85da
* Content: [C++를 이용한 Windows 프로그래밍 개요](https://docs.microsoft.com/ko-kr/cpp/windows/overview-of-windows-programming-in-cpp?view=vs-2019#feedback)
* Content Source: [docs/windows/overview-of-windows-programming-in-cpp.md](https://github.com/MicrosoftDocs/cpp-docs.ko-kr/blob/live/docs/windows/overview-of-windows-programming-in-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-windows**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by srvbpigh** [comment]
Hello, @stargt
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by drvoss** [comment]
@stargt @srvbpigh 
I have a fix in PRs #855.

**Comment by CeciAc** [comment]
안녕하세요, @stargt 님.  
 피드백을 주셔서 감사합니다. 
 당사의 언어 팀이 귀하의 언어 제안을 검토하고 수용했습니다. 귀하의 피드백을 반영하여 Docs 사이트의 업데이트된 문서의 다음 페이지 https://docs.microsoft.com/ko-kr/cpp/windows/overview-of-windows-programming-in-cpp?view=vs-2019#feedback 에 게시했습니다.  
 당사의 문서에 대한 귀하의 기여에 진심으로 감사 드리며 소중한 피드백을 계속 주시기 바랍니다. 
 감사합니다. 
Microsoft DOCS 국제 팀
