### ISSUE TITLE
오류 및 예외 처리(모던 C++)

### ISSUE THREAD

**Issue by bhoh** [MicrosoftDocs/cpp-docs.ko-kr#854]
다수 오타 비문 존재합니다

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 808812eb-d44a-e405-70ed-4d15ed9be975
* Version Independent ID: a3144c13-db26-9dbc-30d8-ae6ca52457af
* Content: [오류 및 예외 처리(모던 C++)](https://docs.microsoft.com/ko-kr/cpp/cpp/errors-and-exception-handling-modern-cpp?view=vs-2019#feedback)
* Content Source: [docs/cpp/errors-and-exception-handling-modern-cpp.md](https://github.com/MicrosoftDocs/cpp-docs.ko-kr/blob/live/docs/cpp/errors-and-exception-handling-modern-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by srvbpigh** [comment]
Hello, @bhoh
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
안녕하세요. @bhoh 님,
댓글을 남겨 주셔서 감사드리며 Microsoft는 docs.microsoft.com의 환경을 개선하기 위해 노력하고 있습니다. 그러나 귀하의 의견을 처리하기 위해서는 추가 정보가 필요합니다. 자세한 정보를 제공하고 댓글에 대해 명확하게 설명해 주실 수 있으신지요?
감사합니다.
Microsoft DOCS International 팀

**Comment by bhoh** [comment]
Many typos and grammatically wrong santence exits. It seems that translation algrithm couldn't translate English preposition. Also, some Korean character spacing is wrong.

For example, "두 경우 모두,가 호출자가 코드를 인식 하 고 적절 하 게 응답할 수 있습니다." this sentance is understandable. But '모두,가' is wrong(could be removed), and '인식 하 고 적절 하 게' should be corrected like '인식하고 적절하게'.

"에 시도 예외인 경우 차단 발생 됩니다" this sentance is totally wrong. just mechanical replacement of English. Translator(Korean to English) translate this sentance like "An attempt to block an exception is raised"
. 

The original sentance

"In the try block, if an exception is thrown it will be caught by the first associated catch block whose type matches that of the exception."

could be like "try 블록에서 예외가 발생하면 해당 예외 타입과 첫째로 연관되는 catch 블록에 포착됩니다"

**Comment by CeciAc** [comment]
Hello, @bhoh
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by drvoss** [comment]
@bhoh @CeciAc 
I have a fix in PRs #856.

**Comment by CeciAc** [comment]
안녕하세요, @bhoh님. 
 귀하의 기여에 매우 감사 드립니다. 당사의 팀에서 귀하의 피드백을 검토한 결과 이 문제는 이미 기록된 것으로 나타났습니다. 
 문제 https://github.com/MicrosoftDocs/cpp-docs.ko-kr/pull/856 를 확인하세요. 이 문제는 중복되기 때문에 종료하겠습니다. 
 감사합니다. 
Microsoft DOCS 국제 팀
