### ISSUE TITLE
ㄴㅇㄹㄴㅇㄹㅇㄹ

### ISSUE THREAD

**Issue by wellbiahck** [MicrosoftDocs/cpp-docs.ko-kr#927]
[여기에 피드백 입력]

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 17c9f501-4f24-7f53-90f9-c8375802e73f
* Version Independent ID: 0126e007-877f-f21c-266e-4b1fcce0c102
* Content: [Variadic 매크로](https://docs.microsoft.com/ko-kr/cpp/preprocessor/variadic-macros?view=vs-2019)
* Content Source: [docs/preprocessor/variadic-macros.md](https://github.com/MicrosoftDocs/cpp-docs.ko-kr/blob/live/docs/preprocessor/variadic-macros.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by srvbpigh** [comment]
Hello, @wellbiahck
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
empty feedback
