### ISSUE TITLE
I want to know how to input Large Array data.

### ISSUE THREAD

**Issue by SKSON** [MicrosoftDocs/cpp-docs.ko-kr#955]
I want to know how to input large array data.
for raytracing, I need more than 10 millions ray(point3d, vector3d) data to calculate.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: e58e07cc-2b1b-668a-5d9d-73afd80ce1c6
* Version Independent ID: 2b3cbb85-9f6c-2ef2-285a-5af0dc64e31d
* Content: [C++ AMP 개요](https://docs.microsoft.com/ko-kr/cpp/parallel/amp/cpp-amp-overview?view=vs-2019#feedback)
* Content Source: [docs/parallel/amp/cpp-amp-overview.md](https://github.com/MicrosoftDocs/cpp-docs.ko-kr/blob/live/docs/parallel/amp/cpp-amp-overview.md)
* Product: **visual-cpp**
* Technology: **cpp-parallel**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by srvbpigh** [comment]
Hello, @SKSON
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @SKSON

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
