### ISSUE TITLE
I think this keyword should not be translated

### ISSUE THREAD

**Issue by yongjun823** [MicrosoftDocs/cpp-docs.ko-kr#964]
Some of the keywords in the current article are translated and displayed in Korean.
example) ``struct``-> ``구조체``, ``class``-> ``클래스``

However, most Korean documents and books use ``this`` keyword in English without translation.
In the current document, the this keyword appears translated.
This can confuse people in reading the document.
It is recommended to use this keyword part without translation.
Thank you

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: a7120637-f004-ce7f-35cd-0c745890e638
* Version Independent ID: f26eb90c-8fd8-631d-ca14-3b5df8da7e35
* Content: [this 포인터](https://docs.microsoft.com/ko-kr/cpp/cpp/this-pointer?view=vs-2019#feedback)
* Content Source: [docs/cpp/this-pointer.md](https://github.com/MicrosoftDocs/cpp-docs.ko-kr/blob/live/docs/cpp/this-pointer.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by srvbpigh** [comment]
Hello, @yongjun823
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Hello, @yongjun823,

Thank you for your feedback. 

Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ko-kr/cpp/cpp/this-pointer?view=vs-2019#feedback.  

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback. 

Kind regards, 

Microsoft DOCS International Team
