### ISSUE TITLE
Header naming is invalid

### ISSUE THREAD

**Issue by yongjun823** [MicrosoftDocs/cpp-docs.ko-kr#985]
In general, C++ header names  are written in English.
ex) ``<iostream>``, ``<algorithm>``

Below is what is shown in the current document.  
스마트 포인터는 [\<메모리 >](../standard-library/memory.md) 헤더 파일의 `std` 네임 스페이스에 정의 됩니다.

Header file name has been translated.
The part marked ``<메모리>`` should be marked with ``<memory>``, the header name for c ++.

Thank you

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 8b4175eb-1766-9810-aa25-ea33f30dc1d5
* Version Independent ID: 46823f31-1bbb-dcd4-3618-9125283e64a0
* Content: [스마트 포인터(최신 C++)](https://docs.microsoft.com/ko-kr/cpp/cpp/smart-pointers-modern-cpp?view=vs-2019)
* Content Source: [docs/cpp/smart-pointers-modern-cpp.md](https://github.com/MicrosoftDocs/cpp-docs.ko-kr/blob/live/docs/cpp/smart-pointers-modern-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by srvbpigh** [comment]
Hello, @yongjun823
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by V-vafune** [comment]
안녕하세요, @yongjun823 님.  

피드백을 주셔서 감사합니다. 문제의 페이지가 기계 번역되어 항상 완벽하게 이해할 수 있는 것은 아닙니다. 최근에 오른쪽에 "영어로 읽기" 옵션이 추가되어 언어 설정을 변경하지 않고도 영어 버전으로 전환할 수 있습니다.  

감사합니다. 

Microsoft DOCS 국제 팀
