### ISSUE TITLE
소스코드가 잘못되었습니다.

### ISSUE THREAD

**Issue by jinwho** [MicrosoftDocs/cpp-docs.ko-kr#987]
https://docs.microsoft.com/ko-kr/cpp/cpp/raw-pointers?view=vs-2019#initialization-and-member-access
여기보면 func_A(mc); 이렇게 호출하는데 mc는 MyClass타입인데 MyClass*를 받는 함수의 인자로 보내고 있습니다.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 2284bc5b-569d-81ee-0b8d-38c711c92656
* Version Independent ID: d448ee76-816d-67a9-6c1d-19da30933822
* Content: [원시 포인터(C++)](https://docs.microsoft.com/ko-kr/cpp/cpp/raw-pointers?view=vs-2019#initialization-and-member-access)
* Content Source: [docs/cpp/raw-pointers.md](https://github.com/MicrosoftDocs/cpp-docs.ko-kr/blob/live/docs/cpp/raw-pointers.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by srvbpigh** [comment]
Hello, @jinwho
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/cpp-docs #2119](https://github.com/MicrosoftDocs/cpp-docs/issues/2119) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
안녕하세요, @jinwho님.  

귀하의 기여에 매우 감사 드립니다. 귀하의 피드백은 원본 설명서와 관련되어 있습니다.  

따라서 이 문제를 영어 리포지토리에 마이그레이션하고 있습니다. 여기 - https://github.com/MicrosoftDocs/cpp-docs/issues/2119에서 문제 상태를 확인하세요.  

당사 문서에 대한 귀하의 기여에 진심으로 감사 드립니다.   

감사합니다.  
Microsoft DOCS 국제 팀
