### ISSUE TITLE
오타 수정

### ISSUE THREAD

**Issue by simkyuwon** [MicrosoftDocs/cpp-docs.ko-kr#988]
"캡처 절에 캡처-기본 &포함 된 경우 해당 캡처 절의 capture에 & identifier형식이 있을 수 identifier 없습니다. "에서 identifier를 빼야 할 것 같습니다.
그리고 capture-default가 캡처-기본값, 캡처-기본 두가지로 번역되어 있는데 캡처-기본값으로 통일하는게 나을 것 같습니다.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 437be494-4752-c2de-a8c0-c4bc8563ddb4
* Version Independent ID: 51317bb8-4c01-146a-f1a7-eba0e54cb5e4
* Content: [C++의 람다 식](https://docs.microsoft.com/ko-kr/cpp/cpp/lambda-expressions-in-cpp?view=vs-2019)
* Content Source: [docs/cpp/lambda-expressions-in-cpp.md](https://github.com/MicrosoftDocs/cpp-docs.ko-kr/blob/live/docs/cpp/lambda-expressions-in-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by srvbpigh** [comment]
Hello, @simkyuwon
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
안녕하세요 @simkyuwon  님, 

기여해 주셔서 감사합니다. 

기계 번역된 콘텐츠의 번역 문제와 관련하여 기여해 주신 부분이 현재 수락되어 있지 않습니다. 

Microsoft는 사람이 번역한 콘텐츠와 관련하여 보내 주시는 피드백과 제안을 소중히 여깁니다. 사람이 번역한 콘텐츠는 기계 번역 엔진을 학습시키는 데 사용되므로 기여해 주신 부분은 시간이 지나면서 사람 번역과 기계 번역 모두의 품질을 향상합니다. 

각 콘텐츠 파일의 헤더에 있는 ms.translationtype 메타데이터 값 “HT”(기계 번역의 경우 “MT”)로 사람이 번역한 항목을 기계 번역된 항목과 구별할 수 있습니다. 

도움 주셔서 감사합니다. 

Microsoft DOCS Global Experience Team 드림
